### PR TITLE
Logan organization

### PR DESCRIPTION
**Pull request by Geivet**
In this pull request, I have implemented the delete button. There is also previous commits containing: testing for the organization table as well as the index page and testing.

### CODE REVIEW

**Comment by briggsrrr** [comment]
it appears you are running into the same issue again with the styker-temp folder... I'm thinking maybe you are running npx stryker run in your team03 directory instead of  team03/frontend. Either way repeating the steps mentioned in the slack should do the trick, maybe try it again before your next commit.

**Review by briggsrrr — APPROVED** [review]
npm tested and stryker tested locally, LGTM

**Review by cyril-wang — CHANGES_REQUESTED** [review]
~~delete button does not delete the row, gets error message "Required request parameter 'orgCode' for method parameter type String is not present"~~ jk im silly

**Review by cyril-wang — APPROVED** [review]
LGTM!

**Pull request merged**
